# Generated by Django 3.1.7 on 2021-03-04 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
